/**
 * Chrome Extension Message Types
 * Used for communication between popup, content script, overlay, and service worker
 */

export type MessageType =
  | 'GET_USER'
  | 'SAVE_WORD'
  | 'TRANSLATE_WORD'
  | 'GET_SETTINGS'
  | 'UPDATE_SETTINGS'
  | 'GET_VOCABULARY'
  | 'DELETE_WORD'
  | 'GET_CAPTIONS'
  | 'FETCH_CAPTIONS'
  | 'CAPTIONS_AVAILABLE'
  | 'CAPTIONS_LOADED'
  | 'AUTH_STATE_CHANGED'
  | 'OVERLAY_READY'
  | 'VIDEO_CHANGED'
  | 'CUE_CHANGE'
  | 'VIDEO_CONTROL'
  | 'GET_WORD_CONTEXT'
  | 'ALL_CAPTIONS'
  | 'CUE_INDEX_CHANGE'
  | 'SEEK_TO_CUE';

export interface Message<T = unknown> {
  type: MessageType;
  payload?: T;
}

// Payload types

export interface SaveWordPayload {
  word: string;
  translation: string;
  language: string;
  contextSentence?: string;
  videoId?: string;
  videoTitle?: string;
  pronunciation?: string;
  partOfSpeech?: string;
}

export interface TranslateWordPayload {
  word: string;
  fromLang: string;
  toLang: string;
}

export interface FetchCaptionsPayload {
  baseUrl: string;
}

export interface CaptionsAvailablePayload {
  videoId: string;
  tracks: CaptionTrack[];
}

export interface CaptionTrack {
  languageCode: string;
  languageName: string;
  baseUrl: string;
  isAutoGenerated: boolean;
  isTranslatable: boolean;
}

export interface CueChangePayload {
  cue: SubtitleCue | null;
  currentTime: number;
}

export interface SubtitleCue {
  startTime: number;
  endTime: number;
  text: string;
  words: WordToken[];
}

export interface WordToken {
  word: string;
  startTime?: number;
  endTime?: number;
  index: number;
}

// Response types

export interface TranslationResponse {
  translation: string;
  source: 'mymemory' | 'libretranslate' | 'google-free';
  pronunciation?: string;
  partOfSpeech?: string;
  definitions?: string[];
}

export interface MessageResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
}

// Video control payload
export interface VideoControlPayload {
  action: 'pause' | 'play' | 'toggle';
}

// AI word context payloads
export interface WordContextPayload {
  word: string;
  sentence: string;
  targetLanguage: string;
  nativeLanguage: string;
}

export interface WordContextResponse {
  definition: string;
  partOfSpeech: string;
  examples: string[];
  pronunciation?: string;
  translation: string;
}

// Lyrics-style caption payloads
export interface AllCaptionsPayload {
  captions: SubtitleCue[];
  translatedCaptions: SubtitleCue[];
}

export interface CueIndexChangePayload {
  currentIndex: number;
  cue: SubtitleCue | null;
  translatedText?: string | null;
}

export interface SeekToCuePayload {
  time: number;
}
