/**
 * Kalaama Content Script
 * Injected into YouTube pages to detect videos, extract captions,
 * and send them to the side panel
 */

import { extractCaptions, fetchCaptionContent, type CaptionTrack } from './subtitle-extractor';
import { parseSubtitles } from './subtitle-parser';
import { VideoSyncService, type ParsedSubtitle } from './video-sync';

class KalaamaContentScript {
  private videoSync: VideoSyncService | null = null;
  private subtitles: ParsedSubtitle[] = [];
  private translatedSubtitles: ParsedSubtitle[] = [];
  private currentVideoId: string | null = null;
  private currentLanguage: string | null = null;
  private nativeLanguage: string = 'en';
  private availableTracks: CaptionTrack[] = [];

  constructor() {
    this.init();
  }

  private async init(): Promise<void> {
    console.log('[Kalaama] Content script initialized');

    // Load user settings
    await this.loadSettings();

    // Wait for YouTube player to be ready
    await this.waitForPlayer();

    // Detect video changes
    this.observeVideoChanges();

    // Listen for messages from popup/service worker/side panel
    chrome.runtime.onMessage.addListener(this.handleMessage.bind(this));

    // Initial video detection
    this.onVideoChange();
  }

  private async loadSettings(): Promise<void> {
    try {
      const response = await chrome.runtime.sendMessage({ type: 'GET_SETTINGS' });
      if (response?.native_language) {
        this.nativeLanguage = response.native_language;
        console.log('[Kalaama] Native language:', this.nativeLanguage);
      }
    } catch (error) {
      console.warn('[Kalaama] Failed to load settings:', error);
    }
  }

  private async waitForPlayer(): Promise<void> {
    return new Promise((resolve) => {
      const check = () => {
        const player = document.querySelector('video.html5-main-video');
        if (player) {
          resolve();
        } else {
          setTimeout(check, 500);
        }
      };
      check();
    });
  }

  private observeVideoChanges(): void {
    // Observe URL changes for SPA navigation
    let lastUrl = location.href;

    const observer = new MutationObserver(() => {
      if (location.href !== lastUrl) {
        lastUrl = location.href;
        this.onVideoChange();
      }
    });

    observer.observe(document.body, {
      childList: true,
      subtree: true,
    });

    // Also listen for YouTube's navigation events
    window.addEventListener('yt-navigate-finish', () => this.onVideoChange());
  }

  private async onVideoChange(): Promise<void> {
    const videoId = this.getVideoId();
    if (!videoId || videoId === this.currentVideoId) return;

    console.log('[Kalaama] Video changed:', videoId);
    this.currentVideoId = videoId;

    // Reset state
    this.subtitles = [];
    this.translatedSubtitles = [];
    this.availableTracks = [];
    if (this.videoSync) {
      this.videoSync.destroy();
      this.videoSync = null;
    }

    // Notify side panel that video changed
    this.sendToSidePanel({
      type: 'VIDEO_INFO',
      payload: {
        videoId,
        title: this.getVideoTitle(),
        language: null
      }
    });

    // Wait a bit for YouTube to fully load
    await new Promise((resolve) => setTimeout(resolve, 1000));

    // Extract captions
    try {
      const tracks = await extractCaptions(videoId);
      this.availableTracks = tracks;
      console.log('[Kalaama] Found caption tracks:', tracks.map(t => t.languageCode));

      if (tracks.length > 0) {
        // Prefer non-auto-generated track, fallback to auto
        const preferredTrack =
          tracks.find((t) => !t.isAutoGenerated) || tracks[0];

        await this.loadCaptions(preferredTrack);

        // Try to load native language track for translation
        const nativeTrack = tracks.find(
          (t) => t.languageCode === this.nativeLanguage ||
                 t.languageCode.startsWith(this.nativeLanguage + '-')
        );

        if (nativeTrack && nativeTrack.languageCode !== preferredTrack.languageCode) {
          await this.loadTranslatedCaptions(nativeTrack);
        }

        // Notify side panel
        this.sendToSidePanel({
          type: 'CAPTION_STATUS',
          payload: {
            connected: true,
            hasCaptions: true,
            trackCount: tracks.length,
            language: preferredTrack.languageCode,
            hasNativeTrack: !!nativeTrack && nativeTrack.languageCode !== preferredTrack.languageCode,
            availableLanguages: tracks.map(t => t.languageCode)
          }
        });
      } else {
        this.sendToSidePanel({
          type: 'CAPTION_STATUS',
          payload: {
            connected: true,
            hasCaptions: false
          }
        });
      }
    } catch (error) {
      console.error('[Kalaama] Failed to extract captions:', error);
      this.sendToSidePanel({
        type: 'CAPTION_STATUS',
        payload: {
          connected: true,
          hasCaptions: false,
          error: (error as Error).message
        }
      });
    }
  }

  private async loadTranslatedCaptions(track: CaptionTrack): Promise<void> {
    try {
      console.log('[Kalaama] Loading translated captions:', track.languageName);
      const content = await fetchCaptionContent(track.baseUrl);
      this.translatedSubtitles = parseSubtitles(content);
      console.log('[Kalaama] Parsed translated subtitles:', this.translatedSubtitles.length);
    } catch (error) {
      console.warn('[Kalaama] Failed to load translated captions:', error);
      this.translatedSubtitles = [];
    }
  }

  private async loadCaptions(track: CaptionTrack): Promise<void> {
    try {
      console.log('[Kalaama] Loading captions:', track.languageName);

      const content = await fetchCaptionContent(track.baseUrl);
      this.subtitles = parseSubtitles(content);
      this.currentLanguage = track.languageCode;

      console.log('[Kalaama] Parsed subtitles:', this.subtitles.length);

      // Notify side panel with video info
      this.sendToSidePanel({
        type: 'VIDEO_INFO',
        payload: {
          videoId: this.currentVideoId,
          title: this.getVideoTitle(),
          language: track.languageCode
        }
      });

      // Setup video sync
      const video = document.querySelector('video.html5-main-video') as HTMLVideoElement;
      if (video) {
        this.videoSync = new VideoSyncService(video, this.subtitles);
        this.videoSync.onCueChange((cue) => {
          // Find matching translated cue
          let translatedText: string | null = null;
          if (cue && this.translatedSubtitles.length > 0) {
            const translatedCue = this.findMatchingCue(cue.startTime, this.translatedSubtitles);
            translatedText = translatedCue?.text || null;
          }

          // Send cue to side panel via service worker
          this.sendToSidePanel({
            type: 'CAPTION_CUE_CHANGE',
            payload: cue ? { ...cue, translatedText } : null
          });
        });
      }
    } catch (error) {
      console.error('[Kalaama] Failed to load captions:', error);
    }
  }

  private findMatchingCue(time: number, subtitles: ParsedSubtitle[]): ParsedSubtitle | null {
    // Binary search for efficiency
    let low = 0;
    let high = subtitles.length - 1;

    while (low <= high) {
      const mid = Math.floor((low + high) / 2);
      const cue = subtitles[mid];

      if (time >= cue.startTime && time <= cue.endTime) {
        return cue;
      } else if (time < cue.startTime) {
        high = mid - 1;
      } else {
        low = mid + 1;
      }
    }

    return null;
  }

  /**
   * Send message to side panel via service worker
   */
  private async sendToSidePanel(message: { type: string; payload: unknown }): Promise<void> {
    try {
      await chrome.runtime.sendMessage(message);
    } catch (error) {
      // Side panel might not be open, that's OK
      console.debug('[Kalaama] Could not send to side panel:', error);
    }
  }

  private handleMessage(
    message: { type: string; payload?: unknown },
    sender: chrome.runtime.MessageSender,
    sendResponse: (response?: unknown) => void
  ): boolean {
    switch (message.type) {
      case 'GET_CAPTIONS':
        sendResponse({ subtitles: this.subtitles });
        break;

      case 'GET_VIDEO_INFO':
        sendResponse({
          videoId: this.currentVideoId,
          title: this.getVideoTitle(),
          language: this.currentLanguage
        });
        break;

      case 'GET_CURRENT_CAPTION':
        // Send current state to side panel
        if (this.videoSync) {
          const currentCue = this.videoSync.getCurrentCue();
          this.sendToSidePanel({
            type: 'CAPTION_CUE_CHANGE',
            payload: currentCue
          });
        }
        this.sendToSidePanel({
          type: 'VIDEO_INFO',
          payload: {
            videoId: this.currentVideoId,
            title: this.getVideoTitle(),
            language: this.currentLanguage
          }
        });
        this.sendToSidePanel({
          type: 'CAPTION_STATUS',
          payload: {
            connected: true,
            hasCaptions: this.subtitles.length > 0
          }
        });
        sendResponse({ received: true });
        break;

      default:
        sendResponse({ error: 'Unknown message type' });
    }

    return true;
  }

  private getVideoId(): string | null {
    const url = new URL(location.href);
    return url.searchParams.get('v');
  }

  private getVideoTitle(): string {
    const titleElement = document.querySelector(
      'h1.ytd-video-primary-info-renderer, h1.ytd-watch-metadata'
    );
    return titleElement?.textContent?.trim() || '';
  }
}

// Initialize
new KalaamaContentScript();
