/**
 * Kalaama Content Script
 * Injected into YouTube pages to detect videos, extract captions,
 * and send them to the side panel
 */

import { extractCaptions, fetchCaptionContent, type CaptionTrack } from './subtitle-extractor';
import { parseSubtitles } from './subtitle-parser';
import { VideoSyncService, type ParsedSubtitle } from './video-sync';

class KalaamaContentScript {
  private videoSync: VideoSyncService | null = null;
  private subtitles: ParsedSubtitle[] = [];
  private translatedSubtitles: ParsedSubtitle[] = [];
  private currentVideoId: string | null = null;
  private currentLanguage: string | null = null;
  private nativeLanguage: string = 'en';
  private availableTracks: CaptionTrack[] = [];

  constructor() {
    this.init();
  }

  private async init(): Promise<void> {
    console.log('[Kalaama] Content script initialized');

    // Load user settings
    await this.loadSettings();

    // Wait for YouTube player to be ready
    await this.waitForPlayer();

    // Detect video changes
    this.observeVideoChanges();

    // Listen for messages from popup/service worker/side panel
    chrome.runtime.onMessage.addListener(this.handleMessage.bind(this));

    // Initial video detection
    this.onVideoChange();
  }

  private async loadSettings(): Promise<void> {
    try {
      const response = await chrome.runtime.sendMessage({ type: 'GET_SETTINGS' });
      if (response?.native_language) {
        this.nativeLanguage = response.native_language;
        console.log('[Kalaama] Native language:', this.nativeLanguage);
      }
    } catch (error) {
      console.warn('[Kalaama] Failed to load settings:', error);
    }
  }

  private async waitForPlayer(): Promise<void> {
    return new Promise((resolve) => {
      const check = () => {
        const player = document.querySelector('video.html5-main-video');
        if (player) {
          resolve();
        } else {
          setTimeout(check, 500);
        }
      };
      check();
    });
  }

  private observeVideoChanges(): void {
    // Observe URL changes for SPA navigation
    let lastUrl = location.href;

    const observer = new MutationObserver(() => {
      if (location.href !== lastUrl) {
        lastUrl = location.href;
        this.onVideoChange();
      }
    });

    observer.observe(document.body, {
      childList: true,
      subtree: true,
    });

    // Also listen for YouTube's navigation events
    window.addEventListener('yt-navigate-finish', () => this.onVideoChange());
  }

  private async onVideoChange(): Promise<void> {
    const videoId = this.getVideoId();
    if (!videoId || videoId === this.currentVideoId) return;

    console.log('[Kalaama] Video changed:', videoId);
    this.currentVideoId = videoId;

    // Reset state
    this.subtitles = [];
    this.translatedSubtitles = [];
    this.availableTracks = [];
    if (this.videoSync) {
      this.videoSync.destroy();
      this.videoSync = null;
    }

    // Notify side panel that video changed
    this.sendToSidePanel({
      type: 'VIDEO_INFO',
      payload: {
        videoId,
        title: this.getVideoTitle(),
        language: null
      }
    });

    // Wait a bit for YouTube to fully load
    await new Promise((resolve) => setTimeout(resolve, 1000));

    // Extract captions
    try {
      const tracks = await extractCaptions(videoId);
      this.availableTracks = tracks;
      console.log('[Kalaama] Found caption tracks:', tracks.map(t => t.languageCode));

      if (tracks.length > 0) {
        // Prefer non-auto-generated track, fallback to auto
        const preferredTrack =
          tracks.find((t) => !t.isAutoGenerated) || tracks[0];

        await this.loadCaptions(preferredTrack);

        // Try to load native language track for translation
        const nativeTrack = tracks.find(
          (t) => t.languageCode === this.nativeLanguage ||
                 t.languageCode.startsWith(this.nativeLanguage + '-')
        );

        if (nativeTrack && nativeTrack.languageCode !== preferredTrack.languageCode) {
          await this.loadTranslatedCaptions(nativeTrack);
        }

        // Notify side panel
        this.sendToSidePanel({
          type: 'CAPTION_STATUS',
          payload: {
            connected: true,
            hasCaptions: true,
            trackCount: tracks.length,
            language: preferredTrack.languageCode,
            hasNativeTrack: !!nativeTrack && nativeTrack.languageCode !== preferredTrack.languageCode,
            availableLanguages: tracks.map(t => t.languageCode)
          }
        });
      } else {
        this.sendToSidePanel({
          type: 'CAPTION_STATUS',
          payload: {
            connected: true,
            hasCaptions: false
          }
        });
      }
    } catch (error) {
      console.error('[Kalaama] Failed to extract captions:', error);
      this.sendToSidePanel({
        type: 'CAPTION_STATUS',
        payload: {
          connected: true,
          hasCaptions: false,
          error: (error as Error).message
        }
      });
    }
  }

  private async loadTranslatedCaptions(track: CaptionTrack): Promise<void> {
    try {
      console.log('[Kalaama] Loading translated captions:', track.languageName);
      const content = await fetchCaptionContent(track.baseUrl);
      this.translatedSubtitles = parseSubtitles(content);
      console.log('[Kalaama] Parsed translated subtitles:', this.translatedSubtitles.length);
    } catch (error) {
      console.warn('[Kalaama] Failed to load translated captions:', error);
      this.translatedSubtitles = [];
    }
  }

  private async loadCaptions(track: CaptionTrack): Promise<void> {
    try {
      console.log('[Kalaama] Loading captions:', track.languageName);

      const content = await fetchCaptionContent(track.baseUrl);
      this.subtitles = parseSubtitles(content);
      this.currentLanguage = track.languageCode;

      console.log('[Kalaama] Parsed subtitles:', this.subtitles.length);

      // Notify side panel with video info
      this.sendToSidePanel({
        type: 'VIDEO_INFO',
        payload: {
          videoId: this.currentVideoId,
          title: this.getVideoTitle(),
          language: track.languageCode
        }
      });

      // Setup video sync
      const video = document.querySelector('video.html5-main-video') as HTMLVideoElement;
      if (video) {
        this.videoSync = new VideoSyncService(video, this.subtitles);
        this.videoSync.onCueChange((cue, cueIndex) => {
          // Find matching translated cue using multiple strategies
          let translatedText: string | null = null;
          if (cue && this.translatedSubtitles.length > 0) {
            const translatedCue = this.findMatchingCue(cue.startTime, this.translatedSubtitles, {
              currentIndex: cueIndex,
              tolerance: 0.5 // 500ms tolerance for fuzzy matching
            });
            translatedText = translatedCue?.text || null;
          }

          // Send cue index change to side panel (for lyrics-style display)
          this.sendToSidePanel({
            type: 'CUE_INDEX_CHANGE',
            payload: {
              currentIndex: cueIndex,
              cue: cue ? { ...cue, translatedText } : null,
              translatedText
            }
          });
        });

        // Send all captions after setup (for lyrics-style display)
        this.sendToSidePanel({
          type: 'ALL_CAPTIONS',
          payload: {
            captions: this.subtitles,
            translatedCaptions: this.translatedSubtitles
          }
        });
      }
    } catch (error) {
      console.error('[Kalaama] Failed to load captions:', error);
    }
  }

  /**
   * Find matching cue using multiple strategies:
   * 1. Exact time match (binary search)
   * 2. Index-based match (same position in translated track)
   * 3. Fuzzy time match (nearest within tolerance)
   */
  private findMatchingCue(
    time: number,
    subtitles: ParsedSubtitle[],
    options?: { currentIndex?: number; tolerance?: number }
  ): ParsedSubtitle | null {
    if (subtitles.length === 0) return null;

    // Strategy 1: Exact time match (binary search)
    const exactMatch = this.exactTimeMatch(time, subtitles);
    if (exactMatch) return exactMatch;

    // Strategy 2: Index-based match (useful when tracks have same structure)
    const currentIndex = options?.currentIndex;
    if (currentIndex !== undefined && currentIndex >= 0 && currentIndex < subtitles.length) {
      const indexCue = subtitles[currentIndex];
      // Accept if reasonably close in time (within 2 seconds)
      if (Math.abs(indexCue.startTime - time) < 2.0) {
        return indexCue;
      }
    }

    // Strategy 3: Fuzzy time match (find nearest within tolerance)
    const tolerance = options?.tolerance ?? 0.5; // 500ms default
    return this.fuzzyTimeMatch(time, subtitles, tolerance);
  }

  private exactTimeMatch(time: number, subtitles: ParsedSubtitle[]): ParsedSubtitle | null {
    let low = 0;
    let high = subtitles.length - 1;

    while (low <= high) {
      const mid = Math.floor((low + high) / 2);
      const cue = subtitles[mid];

      if (time >= cue.startTime && time <= cue.endTime) {
        return cue;
      } else if (time < cue.startTime) {
        high = mid - 1;
      } else {
        low = mid + 1;
      }
    }

    return null;
  }

  private fuzzyTimeMatch(time: number, subtitles: ParsedSubtitle[], tolerance: number): ParsedSubtitle | null {
    let bestMatch: ParsedSubtitle | null = null;
    let bestDistance = Infinity;

    for (const cue of subtitles) {
      // Check if time is within cue range (with tolerance)
      const startDistance = Math.abs(cue.startTime - time);
      const endDistance = Math.abs(cue.endTime - time);
      const minDistance = Math.min(startDistance, endDistance);

      // If time is within the cue range, distance is 0
      const distance = (time >= cue.startTime && time <= cue.endTime) ? 0 : minDistance;

      if (distance < bestDistance && distance <= tolerance) {
        bestDistance = distance;
        bestMatch = cue;
      }

      // Early exit if we've passed the time window
      if (cue.startTime > time + tolerance) break;
    }

    return bestMatch;
  }

  /**
   * Send message to side panel via service worker
   */
  private async sendToSidePanel(message: { type: string; payload: unknown }): Promise<void> {
    try {
      await chrome.runtime.sendMessage(message);
    } catch (error) {
      // Side panel might not be open, that's OK
      console.debug('[Kalaama] Could not send to side panel:', error);
    }
  }

  private handleMessage(
    message: { type: string; payload?: unknown },
    sender: chrome.runtime.MessageSender,
    sendResponse: (response?: unknown) => void
  ): boolean {
    switch (message.type) {
      case 'GET_CAPTIONS':
        sendResponse({ subtitles: this.subtitles });
        break;

      case 'GET_VIDEO_INFO':
        sendResponse({
          videoId: this.currentVideoId,
          title: this.getVideoTitle(),
          language: this.currentLanguage
        });
        break;

      case 'GET_CURRENT_CAPTION':
        // Send current state to side panel
        this.sendToSidePanel({
          type: 'VIDEO_INFO',
          payload: {
            videoId: this.currentVideoId,
            title: this.getVideoTitle(),
            language: this.currentLanguage
          }
        });
        this.sendToSidePanel({
          type: 'CAPTION_STATUS',
          payload: {
            connected: true,
            hasCaptions: this.subtitles.length > 0
          }
        });
        // Send ALL captions for lyrics-style display
        if (this.subtitles.length > 0) {
          this.sendToSidePanel({
            type: 'ALL_CAPTIONS',
            payload: {
              captions: this.subtitles,
              translatedCaptions: this.translatedSubtitles
            }
          });
        }
        // Send current cue index
        if (this.videoSync) {
          const currentCue = this.videoSync.getCurrentCue();
          const currentIndex = this.videoSync.getCurrentCueIndex();
          this.sendToSidePanel({
            type: 'CUE_INDEX_CHANGE',
            payload: {
              currentIndex,
              cue: currentCue,
              translatedText: null
            }
          });
        }
        sendResponse({ received: true });
        break;

      case 'VIDEO_CONTROL':
        this.handleVideoControl(message.payload as { action: 'pause' | 'play' | 'toggle' });
        sendResponse({ success: true });
        break;

      case 'SEEK_TO_CUE':
        this.handleSeekToCue(message.payload as { time: number });
        sendResponse({ success: true });
        break;

      default:
        sendResponse({ error: 'Unknown message type' });
    }

    return true;
  }

  private handleVideoControl(payload: { action: 'pause' | 'play' | 'toggle' }): void {
    const video = document.querySelector('video.html5-main-video') as HTMLVideoElement;
    if (!video) {
      console.warn('[Kalaama] No video element found for control');
      return;
    }

    switch (payload.action) {
      case 'pause':
        video.pause();
        console.log('[Kalaama] Video paused');
        break;
      case 'play':
        video.play();
        console.log('[Kalaama] Video resumed');
        break;
      case 'toggle':
        if (video.paused) {
          video.play();
        } else {
          video.pause();
        }
        break;
    }
  }

  private handleSeekToCue(payload: { time: number }): void {
    const video = document.querySelector('video.html5-main-video') as HTMLVideoElement;
    if (!video) {
      console.warn('[Kalaama] No video element found for seek');
      return;
    }

    if (payload.time !== undefined && payload.time >= 0) {
      video.currentTime = payload.time;
      console.log('[Kalaama] Video seeked to:', payload.time);
    }
  }

  private getVideoId(): string | null {
    const url = new URL(location.href);
    return url.searchParams.get('v');
  }

  private getVideoTitle(): string {
    const titleElement = document.querySelector(
      'h1.ytd-video-primary-info-renderer, h1.ytd-watch-metadata'
    );
    return titleElement?.textContent?.trim() || '';
  }
}

// Initialize
new KalaamaContentScript();
