/**
 * YouTube Caption Extractor
 * Extracts captions from YouTube's internal API
 */
export interface CaptionTrack {
    languageCode: string;
    languageName: string;
    baseUrl: string;
    isAutoGenerated: boolean;
    isTranslatable: boolean;
}
/**
 * Extract available caption tracks from a YouTube video
 */
export declare function extractCaptions(videoId: string): Promise<CaptionTrack[]>;
/**
 * Fetch caption content from a track URL
 */
export declare function fetchCaptionContent(baseUrl: string): Promise<string>;
//# sourceMappingURL=subtitle-extractor.d.ts.map