/**
 * YouTube Caption Extractor
 * Extracts captions from YouTube using multiple methods
 *
 * Method 1: Injected script (most reliable - has page context with cookies)
 * Method 2: Extract from ytInitialPlayerResponse on page
 * Method 3: Service worker fetch (fallback)
 * Method 4: Direct fetch with credentials (last resort)
 */

import { injectCaptionScript, sendToInjectedScript } from './youtube-caption-injector';

export interface CaptionTrack {
  languageCode: string;
  languageName: string;
  baseUrl: string;
  isAutoGenerated: boolean;
  isTranslatable: boolean;
}

interface InjectedCaptionResponse {
  success: boolean;
  content?: string;
  format?: string;
  tracks?: CaptionTrack[];
  error?: string;
}

let injectorReady = false;

async function ensureInjectorReady(): Promise<void> {
  if (injectorReady) return;

  try {
    await injectCaptionScript();
    injectorReady = true;
    console.log('[Kalaama] Caption injector ready');
  } catch (error) {
    console.warn('[Kalaama] Failed to inject caption script:', error);
  }
}

export async function extractCaptions(videoId: string): Promise<CaptionTrack[]> {
  try {
    await ensureInjectorReady();

    if (injectorReady) {
      try {
        const response = await sendToInjectedScript<InjectedCaptionResponse>('GET_CAPTION_TRACKS');
        if (response.tracks && response.tracks.length > 0) {
          console.log('[Kalaama] Got tracks from injected script:', response.tracks.length);
          return response.tracks;
        }
      } catch (error) {
        console.warn('[Kalaama] Injected script track extraction failed:', error);
      }
    }

    const pageResponse = extractFromPage();
    if (pageResponse.length > 0) {
      return pageResponse;
    }

    const fetchedResponse = await fetchAndExtract(videoId);
    return fetchedResponse;
  } catch (error) {
    console.error('[Kalaama] Caption extraction failed:', error);
    return [];
  }
}

function extractFromPage(): CaptionTrack[] {
  try {
    const scripts = document.querySelectorAll('script');

    for (const script of scripts) {
      const content = script.textContent || '';
      const match = content.match(/ytInitialPlayerResponses*=s*({.+?});/s);

      if (match) {
        const playerResponse = JSON.parse(match[1]);
        return extractTracksFromResponse(playerResponse);
      }
    }

    if ((window as unknown as { ytInitialPlayerResponse?: unknown }).ytInitialPlayerResponse) {
      return extractTracksFromResponse(
        (window as unknown as { ytInitialPlayerResponse: unknown }).ytInitialPlayerResponse
      );
    }
  } catch (error) {
    console.warn('[Kalaama] Page extraction failed:', error);
  }

  return [];
}

async function fetchAndExtract(videoId: string): Promise<CaptionTrack[]> {
  try {
    const response = await fetch(`https://www.youtube.com/watch?v=${videoId}`);
    const html = await response.text();

    const match = html.match(/ytInitialPlayerResponses*=s*({.+?});/s);
    if (!match) return [];

    const playerResponse = JSON.parse(match[1]);
    return extractTracksFromResponse(playerResponse);
  } catch (error) {
    console.warn('[Kalaama] Fetch extraction failed:', error);
    return [];
  }
}

function extractTracksFromResponse(playerResponse: unknown): CaptionTrack[] {
  try {
    const response = playerResponse as {
      captions?: {
        playerCaptionsTracklistRenderer?: {
          captionTracks?: Array<{
            baseUrl: string;
            name: { simpleText: string };
            languageCode: string;
            kind?: string;
            isTranslatable: boolean;
          }>;
        };
      };
    };

    const tracks = response?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
    if (!tracks) return [];

    return tracks.map((track) => ({
      languageCode: track.languageCode,
      languageName: track.name.simpleText,
      baseUrl: track.baseUrl,
      isAutoGenerated: track.kind === 'asr',
      isTranslatable: track.isTranslatable,
    }));
  } catch (error) {
    console.warn('[Kalaama] Track extraction failed:', error);
    return [];
  }
}

export async function fetchCaptionContent(baseUrl: string): Promise<string> {
  console.log('[Kalaama] Fetching caption content for:', baseUrl.substring(0, 80));

  await ensureInjectorReady();

  if (injectorReady) {
    try {
      console.log('[Kalaama] Method 1: Trying injected script fetch...');
      const response = await sendToInjectedScript<InjectedCaptionResponse>('FETCH_CAPTIONS', {
        baseUrl,
        format: 'json3'
      });

      if (response.content && response.content.length > 0) {
        console.log('[Kalaama] Got captions from injected script, format:', response.format, 'length:', response.content.length);
        if (response.format === 'xml') {
          return JSON.stringify({ xml: response.content });
        }
        return response.content;
      }
    } catch (error) {
      console.warn('[Kalaama] Injected script fetch failed:', error);
    }
  }

  try {
    console.log('[Kalaama] Method 2: Trying service worker fetch...');
    const response = await chrome.runtime.sendMessage({
      type: 'FETCH_CAPTIONS',
      payload: { baseUrl }
    });

    if (!response.error && response.content && response.content.length > 0) {
      console.log('[Kalaama] Got captions from service worker, format:', response.format);
      if (response.format === 'xml') {
        return JSON.stringify({ xml: response.content });
      }
      return response.content;
    }
  } catch (error) {
    console.warn('[Kalaama] Service worker fetch failed:', error);
  }

  console.log('[Kalaama] Method 3: Trying direct fetch with credentials...');
  return fetchCaptionContentDirect(baseUrl);
}

async function fetchCaptionContentDirect(baseUrl: string): Promise<string> {
  try {
    const response = await fetch(baseUrl, { credentials: 'include', headers: { 'Accept': '*/*' } });
    if (response.ok) {
      const text = await response.text();
      if (text && text.trim().length > 0) {
        const isJson = text.trim().startsWith('{') || text.trim().startsWith('[');
        return isJson ? text : JSON.stringify({ xml: text });
      }
    }
  } catch (error) {
    console.warn('[Kalaama] Direct fetch original URL failed:', error);
  }

  try {
    const url = new URL(baseUrl);
    url.searchParams.set('fmt', 'json3');
    const response = await fetch(url.toString(), { credentials: 'include', headers: { 'Accept': 'application/json, */*' } });
    if (response.ok) {
      const text = await response.text();
      if (text && text.trim().length > 0) return text;
    }
  } catch (error) {
    console.warn('[Kalaama] Direct fetch JSON3 failed:', error);
  }

  try {
    const url = new URL(baseUrl);
    url.searchParams.set('fmt', 'srv3');
    const response = await fetch(url.toString(), { credentials: 'include', headers: { 'Accept': '*/*' } });
    if (response.ok) {
      const text = await response.text();
      if (text && text.trim().length > 0) return JSON.stringify({ xml: text });
    }
  } catch (error) {
    console.warn('[Kalaama] Direct fetch SRV3 failed:', error);
  }

  throw new Error('All caption fetch methods failed');
}
